In [2]:
import numpy as np

In [22]:
#Task1
N = int(input("enter your size : "))

array = np.zeros(N, dtype = int)
print(array)

for i in range(N):
  array[i] = int(input("enter values for the array : "))
print("Original Array :",array)

new_array = np.zeros(N+1, dtype = int)

for j in range(N+1):
  if j == N:
    new_array[j] = int(input("enter the last value for new array : "))
  else:
    new_array[j] = array[j]
print("Resized Array :",new_array)

enter your size : 3
[0 0 0]
enter values for the array : 5
enter values for the array : 8
enter values for the array : 2
Original Array : [5 8 2]
enter the last value for new array : 9
Resized Array : [5 8 2 9]


In [28]:
#Task2
N = int(input("enter your size : "))

array = np.zeros(N, dtype = int)
print(array)

for i in range(N):
  array[i] = int(input("enter values for the array : "))
print("Original Array :",array)

for j in range(N):
  if array[j] > 0:
    array[j] = 1
  elif array[j] < 0:
    array[j] = 0
print("After modifying :",array)

enter your size : 4
[0 0 0 0]
enter values for the array : 3
enter values for the array : 4
enter values for the array : -2
enter values for the array : 1
Original Array : [ 3  4 -2  1]
After modifying : [1 1 0 1]


In [37]:
#Task3
def reversearray(n):
  i = 0
  j = n.size - 1

  while i<j:
    arr1[i],arr1[j] = arr1[j],arr1[i]
    i += 1
    j -= 1
  return n

arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reversearray(arr1)
print(arr1)

[ 7  5 20 12 10]


In [49]:
#Task4
def printpairs (array,sum):
  flag = False
  for i in range(array.size):
    for j in range(i+1,array.size):
      if array[i] + array[j] == sum:
        flag = True
        print(array[i],array[j])

  if flag == False:
    print("No Pair Found")

arr1 = np.array([7,8,10,5,3,4,2])
printpairs(arr1,15)

7 8
10 5


In [70]:
#Task5
vec1 = np.array([1,2,3,7])
vec2 = np.array([4,5,6,9])
# vec1 = np.array([1,2,3])
# vec2 = np.array([4,5,6])

dot_prod = 0

for i in range(vec1.size):
  dot_prod = dot_prod+(vec1[i]*vec2[i])
print("Dot Product",dot_prod)

if dot_prod%2==0:
  for j in range(vec1.size):
    if j%2 == 0:
      vec1[j],vec2[j] = vec2[j],vec1[j]
else:
  for k in range(vec1.size):
    if k%2 != 0:
      vec1[k],vec2[k] = vec2[k],vec1[k]
print(vec1,vec2)

Dot Product 95
[1 5 3 9] [4 2 6 7]


In [3]:
#Task6
size=int(input())
Array=np.zeros(size,dtype=int)

for i in range(size):
  Array[i]=int(input())
print("Orginal Array:",Array)

for i in range(size):
  min_index=i
  for j in range(i+1,size):
    if Array[min_index]>Array[j]:
      min_index=j
  Array[i],Array[min_index]=Array[min_index],Array[i]
  
print("Sorted Array:",Array)

Orginal Array: [3 6 1 2 8 5]
Sorted Array: [1 2 3 5 6 8]


In [77]:
#Task7
def flatten(array):
  row = array.shape[0]
  col = array.shape[1]
  new_array = np.zeros(array.size,dtype= int)
  index = 0
  for i in range(row):
    for j in range(col):
      new_array[index] = array[i][j]
      index += 1
  return new_array

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = flatten(arr1)
print(arr2)

[1 2 3 4 5 6]


In [10]:
#Task8
A = np.array([ [1, 0, 0],[0, 1, 0],[0, 0, 1] ])
counter=0
counter1=0

for i in range(A.shape[0]):
  for j in range(A.shape[1]):
    if A[i][j]!=0 and A[i][j]!=1:
      counter1+=1
    elif i!=j:
      if A[i][j]!=0:
        counter1+=1
    elif i==j:
      if A[i][j]==1:
        counter+=1
if counter1>0:
      print("Not identiy Matrix")
elif counter==len(A):
      print("identity Matrix")

identity Matrix


In [12]:
#Task9
A = np.array([ [1,  5,  12,  1],
               [2,  -4,  6,  7],
               [3,  8,  5,  9],
               [3,  5,  23,  -6] ])
row=A.shape[0]
column=A.shape[1]
sum1=0
sum2=0
for i in range(row):
  for j in range(column):
    if i==j:
      sum1+=A[i][j]
for i in range(row):
  sum2+=A[i][column-1]
  column-=1
print(abs(sum1-sum2))

22


In [11]:
#Task 10.1
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


B=np.zeros(shape=(A.shape[1],A.shape[0]),dtype=int)
for i in range(A.shape[0]):
  for j in range(B.shape[0]):
    B[j][i]=A[i][j]
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
#Task 10.2
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

B=np.zeros(shape=(A.shape[1],A.shape[0]),dtype=int)

for i in range(A.shape[0]):
  for j in range(B.shape[0]):
    B[j][i]=A[i][j]
M=A.shape[0]
N=A.shape[1]
outedA=np.zeros(shape=(B.shape[0],A.shape[1]),dtype=int)

for i in range(N):
  for j in range(N):
    sum=0
    for k in range(M):
      sum+=B[i][k]*A[k][j]
    outedA[i][j]=sum

print(outedA)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [ ]:
#Task11
A = np.array([[4,1,2],[9,3,7]])

M=A.shape[0]
N=A.shape[1]
B=np.zeros(shape=(M,N),dtype=float)

absolutevalue = abs(row-column)
remainder = absolutevalue%M

summation=0

for j in range(N):
    summation+=A[remainder+1][j]
average=summation/N

for i in range(M):
  for j in range(N):
    B[i][j]=A[i][j]*round(average,2)
print(B)