I took the approach where
1. parent = i // 2
2. left child = 2 * i
3. right child = 2 * i +1

In [50]:
import numpy as np

Task 1

In [51]:
class MinHeap:
    def __init__(self, capacity):
        self.__capacity = capacity + 1
        self.__heap = np.zeros(self.__capacity, dtype = 'int')
        self.__size = 0
    
    def capacity(self):
        return self.__capacity
    
    def size(self):
        return self.__size

    def left_child(self, i):
        return 2 * i
    
    def right_child(self, i):
        return 2 * i + 1

    def insert(self, value):
        if self.size() >= self.capacity():
            return "limit exceeded"
        
        self.__size += 1
        self.__heap[self.size()] = value
        self.swim(self.size())

    def swim(self, index):
        if index > 1 and self.__heap[index] < self.__heap[index // 2]:
            self.__heap[index], self.__heap[index // 2] = self.__heap[index // 2], self.__heap[index]
            self.swim(index // 2)

    def sink(self, index):
        smallest = index
        left = self.left_child(index)
        right = self.right_child(index)

        if left <= self.size() and self.__heap[smallest] > self.__heap[left]:
            smallest = left
        if right <= self.size() and self.__heap[smallest] > self.__heap[right]:
            smallest = right

        if smallest != index:
            self.__heap[index], self.__heap[smallest] = self.__heap[smallest], self.__heap[index]
            self.sink(smallest)

    def extractMin(self):
        # if self._size == 0:
        #     return "Heap is empty"
        
        min_val = self.__heap[1]
        self.__heap[1] = self.__heap[self.size()]
        #self.__heap[self.size()] = 0
        self.__size -= 1
        self.sink(1)
        return min_val

    def isEmpty(self):
        if self.size() == 0:
            return True
        else:
            return False

    def top(self):
        if self.__heap[1] != None:
            return self.__heap[1]
        else:
            return "Empty Heap"
        
    def sort(self):
        min_result_array = np.zeros(self.size(), dtype = 'int')
        j = self.__size - 1

        while self.isEmpty() == False:
            min_result_array[j] = int(self.extractMin())
            j -= 1

        return min_result_array

    def print_heap(self):
        for value in range(self.__size + 1):
            print(self.__heap[value], end = " ")

In [52]:
#Driver Code for MinHeap
tester_heap = MinHeap(7)
tester_heap.insert(5)
tester_heap.insert(8)
tester_heap.insert(11)
tester_heap.insert(13)
tester_heap.insert(15)
tester_heap.insert(18)
tester_heap.insert(21)

print("Heap after insertion:")
tester_heap.print_heap()
print()
tester_heap.extractMin()
print("Heap after operating extractMin function:")
tester_heap.print_heap()
print()
print("Heap after performing Heapsort:")
print(tester_heap.sort())

Heap after insertion:
0 5 8 11 13 15 18 21 
Heap after operating extractMin function:
0 8 13 11 21 15 18 
Heap after performing Heapsort:
[21 18 15 13 11  8]


Task 2

In [53]:
class MaxHeap:
    def __init__(self, capacity):
        self.__capacity = capacity + 1
        self.__heap = np.zeros(self.__capacity, dtype = 'int')
        self.__size = 0

    def capacity(self):
        return self.__capacity
    
    def size(self):
        return self.__size
    
    def left_child(self, i):
        return 2 * i
    
    def right_child(self, i):
        return 2 * i + 1

    def insert(self, value):
        if self.size() >= self.capacity():
            return "limit exceeded"
        
        self.__size += 1
        self.__heap[self.size()] = value
        self.swim(self.size())

    def swim(self, index):
        if index > 1 and self.__heap[index] > self.__heap[index // 2]:
            self.__heap[index], self.__heap[index // 2] = self.__heap[index // 2], self.__heap[index]
            self.swim(index // 2)

    def sink(self, index):
        largest = index
        left = self.left_child(index)
        right = self.right_child(index)

        if left <= self.size() and self.__heap[largest] < self.__heap[left]:
            largest = left
        if right <= self.size() and self.__heap[largest] < self.__heap[right]:
            largest = right

        if largest != index:
            self.__heap[index], self.__heap[largest] = self.__heap[largest], self.__heap[index]
            self.sink(largest)

    def extractMax(self):
        # if self._size == 0:
        #     return "Heap is empty"
        
        max_val = self.__heap[1]
        self.__heap[1] = self.__heap[self.__size]
        #self.__heap[self.size()] = 0
        self.__size -= 1
        self.sink(1)
        return max_val

    def isEmpty(self):
        if self.size() == 0:
            return True
        else:
            return False

    def top(self):
        if self.__heap[1] != None:
            return self.__heap[1]
        else:
            return "Empty Heap"
        
    def sort(self):
        max_result_array = np.zeros(self.size(), dtype = 'int')
        j = self.__size - 1

        while self.isEmpty() == False:
            max_result_array[j] = int(self.extractMax())
            j -= 1

        return max_result_array

    def print_heap(self):
        for value in range(self.__size + 1):
            print(self.__heap[value], end = " ")

In [54]:
#Driver Code for MaxHeap
tester_heap = MaxHeap(7)
tester_heap.insert(21)
tester_heap.insert(18)
tester_heap.insert(15)
tester_heap.insert(13)
tester_heap.insert(11)
tester_heap.insert(8)
tester_heap.insert(5)

print("Heap after insertion:")
tester_heap.print_heap()
print()
tester_heap.extractMax()
print("Heap after operating extractMax function:")
tester_heap.print_heap()
print()
print("Heap after performing Heapsort:")
print(tester_heap.sort())

Heap after insertion:
0 21 18 15 13 11 8 5 
Heap after operating extractMax function:
0 18 13 15 5 11 8 
Heap after performing Heapsort:
[ 5  8 11 13 15 18]


Task 3

In [55]:
tasks = np.array([2, 4, 7, 1, 6])
m = 4

machine_heap = MinHeap(m)

for i in range(m):
    machine_heap.insert(0)

for i in range(tasks.size):
    extract = machine_heap.extractMin()
    load = int(extract) + tasks[i]
    machine_heap.insert(load)

machine_heap.print_heap()

0 2 7 4 7 

Task 4

In [56]:
nums = np.array([4, 10, 2, 8, 6, 7])
k = 3

result_arr = np.zeros(k, dtype = 'int')
working_heap = MaxHeap(nums.size)

for i in range(nums.size):
    working_heap.insert(nums[i])

for i in range(k):
    result_arr[i] = working_heap.extractMax()

print(result_arr)

[10  8  7]
